# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://pkg.harness.io/pkg/ct8onj8YTdaXtKaFsYCRLg/org-nuclia-npm/npm/
    token: ${{secrets.DEPENDABOT_TEMP_PLACEHOLDER_TOKEN}}
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries: '*'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 14
