approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: true

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 20160

npmRegistryServer: "https://pkg.harness.io/pkg/ct8onj8YTdaXtKaFsYCRLg/org-nuclia-npm/npm/"

npmScopes:
  jsr:
    npmRegistryServer: "https://pkg.harness.io/pkg/ct8onj8YTdaXtKaFsYCRLg/org-nuclia-npm/npm/"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
