import { IResources } from '../components/RaoWidget/RaoWidget.interface';

export const DEFAULT_RESOURCES: IResources = {
  aria_openchat: 'Open Chat History',
  aria_collapsechat: 'Collapse Chat',
  aria_expandchat: 'Expand Chat',
  aria_closechat: 'Close Chat',
  aria_suggestedprompts: 'Suggested Prompts',
  aria_addprompt: 'Add Prompt',
  aria_notsupported: 'Speech recognition is not supported in this browser',
  aria_stoprecording: 'Stop recording',
  aria_startrecording: 'Start recording',

  intro_title: 'RAO Assistant',
  intro_greetings: 'Hello! How can I assist you today?',

  form_placeholder_default: 'Type your message here...',
  form_placeholder_followup: 'Ask a follow-up',

  meta_page: 'Page',
  meta_jumpto: 'Jump to',
  meta_citation: 'Citation',
  meta_reference: 'Reference',
  meta_source: 'Source',
  meta_unexpectedissue: 'The assistant hit an unexpected issue.',
  meta_step: 'Step',
  meta_agent: 'Agent',
  meta_duration: 'Duration',
  meta_inputtokens: 'Input Tokens',
  meta_outputtokens: 'Output Tokens',
  meta_context: 'Context',
  meta_contextgathered: 'Context Gathered',
  meta_supportingevidence: 'Supporting Evidence',
  meta_questionanalysed: 'Question Analysed',
  meta_evidence: 'Evidence',
  meta_sources: 'Sources',
  meta_citations: 'Citations',
  meta_reasoning: 'Reasoning',
  meta_agentrequest: 'Assistant request',
  feedback_choose: 'Choose one of the options below.',
  feedback_sending: 'Sending your selection…',
  feedback_sent: 'Selection sent',
  feedback_error: 'Unable to send your selection. Please try again.',
  feedback_selected: 'Selected',
};
