server {
  listen 80;
  server_name stashify-auth;
  root /dist/;
  index index.html;
  location / {
      add_header Strict-Transport-Security "max-age=31536000" always;
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-XSS-Protection "0" always;
      # https://www.google.com/recaptcha/ is required by ng-recaptcha (reCAPTCHA v3)
      add_header Content-Security-Policy-Report-Only "script-src 'self' 'sha256-CjFUxFmO8p+HqFTns+8kQJLtkFAEvIT/H4AOPmt0dw0=' 'sha256-EF4DKZpJ0oybAmkbjPx8c9gWIOlaJqBCz0ZNvpIBbeE=' https://cdn.stashify.cloud https://rag.stashify.cloud https://cdn.rag.progress.cloud https://gcp-global-dev-1.nuclia.io https://cdn.gcp-global-dev-1.nuclia.io https://www.googletagmanager.com https://cdn.cookielaw.org https://*.posthog.com https://*.i.posthog.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/; report-uri /api/csp-reports/csp; report-to csp" always;
      add_header Reporting-Endpoints "csp=\"/api/csp-reports/reporting-api/csp\"" always;

      try_files $uri /index.html =404;
  }
  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
      root   /usr/share/nginx/html;
  }
}
