server {
  listen 80;
  server_name stashify-manager;
  root /dist/;
  index index.html;
  location / {
      add_header Strict-Transport-Security "max-age=31536000" always;
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-XSS-Protection "0" always;
      add_header Content-Security-Policy-Report-Only "script-src 'self' https://cdn.stashify.cloud https://rag.stashify.cloud https://cdn.rag.progress.cloud https://gcp-global-dev-1.nuclia.io https://cdn.gcp-global-dev-1.nuclia.io; report-uri /api/csp-reports/csp; report-to csp" always;
      add_header Reporting-Endpoints "csp=\"/api/csp-reports/reporting-api/csp\"" always;

      try_files $uri /index.html =404;
  }
  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
      root   /usr/share/nginx/html;
  }
}
