name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan with Azure Access
        uses: prgs-community/githubactions-reusableworkflows/actions/sonarqube/cli@main
        with:
          sonarqube-token: ${{ secrets.SONAR_TOKEN }}
          akeyless-access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          use-local-runner: 'false'
          project-key: 'nuclia-frontend'
