import { ACTIVITY_LOG_CHAT_SHOW_FIELDS, ActivityLogItem } from '@nuclia/core';
import { MetricsColumnDef, MetricsSidebarField } from '../metrics-column.model';

export const CHAT_ACTIVITY_COLUMNS: MetricsColumnDef[] = [
  {
    key: 'date',
    label: 'activity.column.date',
    value: (item: ActivityLogItem) => item.date ?? null,
    width: '120px',
    group: 'query',
  },
  {
    key: 'question',
    label: 'activity.column.question',
    value: (item: ActivityLogItem) => item.question ?? null,
    width: '1fr',
    group: 'query',
    searchable: true,
  },
  {
    key: 'client_type',
    label: 'activity.column.client-type',
    value: (item: ActivityLogItem) => item.client_type ?? null,
    width: '120px',
    group: 'query',
    searchable: true,
  },
  {
    key: 'answer',
    label: 'activity.column.answer',
    value: (item: ActivityLogItem) => item.answer ?? null,
    width: '1fr',
    group: 'generative',
    searchable: true,
  },
  {
    key: 'total_duration',
    label: 'activity.column.duration',
    value: (item: ActivityLogItem) => item.total_duration ?? null,
    width: '1fr',
    group: 'tokens',
  },
  {
    key: 'id',
    label: 'activity.column.id',
    value: (item: ActivityLogItem) => item.id ?? null,
    width: '100px',
    defaultHidden: true,
    group: 'query',
    searchable: true,
  },
  {
    key: 'model',
    label: 'activity.column.model',
    value: (item: ActivityLogItem) => item.model ?? null,
    width: '140px',
    defaultHidden: true,
    group: 'generative',
  },
  {
    key: 'nuclia_tokens',
    label: 'activity.column.nuclia-tokens',
    value: (item: ActivityLogItem) => item.nuclia_tokens ?? null,
    width: '120px',
    defaultHidden: true,
    group: 'tokens',
  },
  {
    key: 'learning_id',
    label: 'activity.column.learning-id',
    value: (item: ActivityLogItem) => item.learning_id ?? null,
    width: '160px',
    defaultHidden: true,
    group: 'generative',
    searchable: true,
  },
  {
    key: 'status',
    label: 'activity.column.status',
    value: (item: ActivityLogItem) => item.status ?? null,
    width: '100px',
    defaultHidden: true,
    group: 'generative',
  },
  {
    key: 'generative_answer_time',
    label: 'activity.column.generative-answer-time',
    value: (item: ActivityLogItem) => item.generative_answer_time ?? null,
    width: '140px',
    defaultHidden: true,
    group: 'generative',
  },
  {
    key: 'generative_answer_first_chunk_time',
    label: 'activity.column.generative-answer-first-chunk-time',
    value: (item: ActivityLogItem) => item.generative_answer_first_chunk_time ?? null,
    width: '160px',
    defaultHidden: true,
    group: 'generative',
  },
  {
    key: 'generative_reasoning_first_chunk_time',
    label: 'activity.column.generative-reasoning-first-chunk-time',
    value: (item: ActivityLogItem) => item.generative_reasoning_first_chunk_time ?? null,
    width: '180px',
    defaultHidden: true,
    group: 'generative',
  },
  {
    key: 'feedback_good',
    label: 'activity.column.feedback-good',
    value: (item: ActivityLogItem) => (item.feedback_good == null ? null : String(item.feedback_good)),
    width: '100px',
    defaultHidden: true,
    group: 'feedback',
  },
  {
    key: 'feedback_good_all',
    label: 'activity.column.feedback-good-all',
    value: (item: ActivityLogItem) => (item.feedback_good_all == null ? null : String(item.feedback_good_all)),
    width: '120px',
    defaultHidden: true,
    group: 'feedback',
  },
  {
    key: 'feedback_good_any',
    label: 'activity.column.feedback-good-any',
    value: (item: ActivityLogItem) => (item.feedback_good_any == null ? null : String(item.feedback_good_any)),
    width: '120px',
    defaultHidden: true,
    group: 'feedback',
  },
];

export const CHAT_ACTIVITY_SIDEBAR_FIELDS: MetricsSidebarField[] = [
  {
    key: 'reasoning',
    label: 'activity.column.reasoning',
    value: (item: ActivityLogItem) => item.reasoning ?? null,
    expandable: true,
    group: 'generative',
  },
  {
    key: 'feedback_comment',
    label: 'activity.column.details',
    value: (item: ActivityLogItem) => item.feedback_comment ?? null,
    expandable: true,
    group: 'feedback',
  },
];

const EXCLUDED_CHAT_FIELDS: ReadonlySet<string> = new Set([
  'user_id',
  'user_type',
  'audit_metadata',
  'resource_id',
  'token_details',
  'rephrased_question',
  'rag_strategies_names',
  'rag_strategies',
  'retrieved_context',
  'chat_history',
  'remi_scores',
  'feedback',
  'user_request',
]);
export const CHAT_ACTIVITY_SHOW_FIELDS = ACTIVITY_LOG_CHAT_SHOW_FIELDS.filter((f) => !EXCLUDED_CHAT_FIELDS.has(f));
